name: Blue-Green Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 147.93.107.157 >> ~/.ssh/known_hosts

      - name: Deploy Blue-Green
        run: |
          ssh pratik@147.93.107.157 << 'EOF'
            set -e  # Exit if any command fails
            echo "=== Starting deployment process ==="

            # Read current active port from NGINX config
            echo "-- Checking current active port --"
            ACTIVE_PORT=$(awk -F'[:;]' '/proxy_pass http:\/\/localhost:/ {print $3}' /etc/nginx/sites-available/api.buzzbytes.bytebuilderz.xyz | head -n 1)
            echo "Detected ACTIVE_PORT=$ACTIVE_PORT" | tee ~/active_port.log
            
            # Determine deployment strategy
            echo "-- Determining deployment strategy --"
            if [ "$ACTIVE_PORT" = "8000" ]; then
              echo "Current production is on blue (8000), deploying to green (8001)"
              NEW_PORT=8001
              NEW_FOLDER="buzz-bytes-green"
              OLD_FOLDER="buzz-bytes-blue"
            else
              echo "Current production is on green (8001), deploying to blue (8000)"
              NEW_PORT=8000
              NEW_FOLDER="buzz-bytes-blue"
              OLD_FOLDER="buzz-bytes-green"
            fi

            echo "=== Deployment parameters ==="
            echo "NEW_PORT: $NEW_PORT"
            echo "NEW_FOLDER: $NEW_FOLDER"
            echo "OLD_FOLDER: $OLD_FOLDER"

            # Clean up old deployment process
            echo "-- Cleaning up previous $OLD_FOLDER deployment --"
            echo "Attempting to delete PM2 process: $OLD_FOLDER"
            pm2 delete $OLD_FOLDER || echo "No existing $OLD_FOLDER process to delete"
            echo "PM2 list after cleanup:"
            pm2 list

            # Setup deployment directory
            echo "-- Setting up deployment directory: $NEW_FOLDER --"
            mkdir -p ~/$NEW_FOLDER
            cd ~/$NEW_FOLDER
            echo "Current directory: $(pwd)"

            # Update codebase
            echo "-- Updating codebase --"
            if [ ! -d ".git" ]; then
              echo "Cloning fresh repository"
              git clone -b master https://github.com/pratiksarangi7/buzz-bytes-upgraded-backend.git .
            else
              echo "Pulling latest changes"
              git pull origin master
            fi

            # Build process
            echo "-- Installing dependencies --"
            npm install
            echo "-- Generating Prisma client --"
            npx prisma generate
            echo "-- Building project --"
            npm run build

            # Start new deployment
            echo "-- Starting new deployment on port $NEW_PORT --"
            echo "Using PM2 name: $NEW_FOLDER"
            PORT=$NEW_PORT pm2 start npm --name $NEW_FOLDER -- start
            echo "PM2 list after new deployment start:"
            pm2 list

            # Wait for initialization
            echo "-- Waiting 15 seconds for application initialization --"
            sleep 15

            # Health check
            echo "-- Performing health check --"
            HEALTH_CHECK_URL="http://127.0.0.1:$NEW_PORT/health"
            echo "Health check URL: $HEALTH_CHECK_URL"
            HEALTH_OUTPUT=$(curl -s $HEALTH_CHECK_URL)
            echo "Raw health check output: $HEALTH_OUTPUT"
            
            if echo "$HEALTH_OUTPUT" | grep -E -q '"status"\s*:\s*"ok"'; then
              echo "+++ Health check successful +++"
              
              # Update NGINX config
              echo "-- Updating NGINX configuration --"
              echo "Changing proxy_pass to port $NEW_PORT"
              sudo sed -i "s/proxy_pass http:\/\/localhost:[0-9]*/proxy_pass http:\/\/localhost:$NEW_PORT/" /etc/nginx/sites-available/api.buzzbytes.bytebuilderz.xyz
              echo "Reloading NGINX"
              sudo systemctl reload nginx
              echo "NGINX reload status: $?"

              # Switch PM2 process
              echo "-- Switching to new deployment --"
              echo "Stopping current buzzbytes-api process"
              pm2 stop buzzbytes-api || echo "No running buzzbytes-api process"
              echo "Deleting buzzbytes-api process"
              pm2 delete buzzbytes-api || echo "No existing buzzbytes-api process"
              echo "Renaming $NEW_FOLDER to buzzbytes-api"
              pm2 restart $NEW_FOLDER --name buzzbytes-api --update-env
              echo "Saving PM2 state"
              pm2 save
              echo "Final PM2 list:"
              pm2 list
            else
              echo "!!! Health check failed !!!"
              echo "Raw health response: $HEALTH_OUTPUT"
              echo "Rolling back deployment"
              pm2 delete $NEW_FOLDER
              echo "Current PM2 list after rollback:"
              pm2 list
              exit 1
            fi

            # Cleanup old deployment
            echo "-- Cleaning up old deployment folder: $OLD_FOLDER --"
            rm -rf ~/$OLD_FOLDER
            echo "Remaining directories:"
            ls -l ~/

            echo "=== Deployment completed successfully ==="
          EOF
