name: Deploy to VPS

on:
  push:
    branches:
      - master # Changed from 'main' to 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 147.93.107.157 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh pratik@147.93.107.157 << 'EOF'
            cd buzz-bytes-backend
            git pull origin master  
            npm install
            npx prisma generate
            pm2 restart buzzbytes-api
          EOF
